### ISSUE TITLE
Could you add easing presets?

### ISSUE THREAD

**Issue by RubenHooijer** [Juce-Assets/Juce-TweenPlayer#1]
In Juce-Feedback you had easing presets, which made it effortless to create the animations.

**Comment by Guillemsc** [comment]
Hi @RubenHooijer thanks for reaching out.

I didn't add easing presets to TweenPlayer since it was a bit redundant to have presets and also the AnimationCurve. 
They are practically the same, but AnimationCurve is the more poweful one, so it's with I ended up sticking with.

AnimationCurve also suports presets! You can define your own by going to the option menu and selecting new.

![image](https://user-images.githubusercontent.com/17142208/149575645-6a614713-d5f2-47c9-841d-38951aa043ac.png)
![image](https://user-images.githubusercontent.com/17142208/149575878-5126d47b-45e4-4e96-afd9-f8d760aacaee.png)

In my opinion, creating your own library is way more powerful than relying on some predefined presets, even If they are convinient at first.

Here you can find the presets that Juce-Feedbacks had, but with its curves:
https://easings.net/

Also another cool website for visualizing animations with curves:
https://cubic-bezier.com/

Since I aim for simplicity, I don't intend on adding presets again, sorry if this causes you any issues, and I hope that at least my explanation helps you in some way.

**Comment by RubenHooijer** [comment]
Yes, it helps. I knew we can make presets, but I dislike them since I can't name them which makes it harder to find the best easing. But I also get that having two different easing implementations is a bit unnecessary.
